apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: eks-flux-dashboards
    files:
      - dashboards/gotk-cluster.json
      - dashboards/gotk-control-plane.json
      - dashboards/nginx-dashboard.json
    options:
      labels:
        grafana_dashboard: "1"
      disableNameSuffixHash: true