apiVersion: flagger.app/v1beta1
kind: MetricTemplate
metadata:
  name: error-rate
  namespace: nginx-ingress
spec:
  provider: 
    type: prometheus
    address: http://kube-prometheus-stack-prometheus.monitoring:9090
  query: |
    100 - rate(
      http_requests_total{
        status!="5.*",
        namespace="{{ namespace }}",
        job="{{ target }}-canary"
      }[{{ interval }}]
    )
    /
    rate(
      http_requests_total{
        namespace="{{ namespace }}",
        job="{{ target }}-canary"
      }[{{ interval }}]
    ) * 100