apiVersion: v1
data:
    token: ENC[AES256_GCM,data:eHr1m4y2WPNHn1h8gb3nnhj6M1f5W7iKTejDpR5Le+JaoBFtDA2SoynjrmotuYRMVr9myq3d/Gk=,iv:V1CjdjoMhsoYIRFsoYRyL03HXmByXDL4IcXZJHv2c2w=,tag:Ekemf8J1IiQGX/TvVJm8YQ==,type:str]
kind: Secret
metadata:
    name: notify-token
    namespace: flux-system
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2021-03-24T09:59:03Z'
    mac: ENC[AES256_GCM,data:FUjAd/aBW8DwYmupwA/5w5WWrHyhBTnJ2732eeFCIGsKXmrBciqjEqvqgde3fNx87EQ3fO5AlErF5y+/nRzuwJqqeiM5O2+xsSh61ZLAnQUiwFPM+bjzxmMFgLbsJIlPJXd3taMU4NUrrUEKbel+XQ9Ml8G6YQMO0NddFpNzv2I=,iv:vRU/f4BJ71/o2vBWihT6rTukRWSXWfnPoZthUD/YRjE=,tag:G9yFTIzeE60MhSaDl8GQRQ==,type:str]
    pgp:
    -   created_at: '2021-03-24T09:59:02Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA3jrBDJ/hPaCARAAjc23nbxSXZv2uCkzkWsKioG8dIF6QJYgLdtbRZ9VBkaj
            gkjkDOPVvj+VyZSDprq6PCLhkKMWGC0nG/5k7K+8P267hC80k81+sMKySrYqKSxR
            N54KuplMvGqeG2LqEzQyGP9ZV41N5qZPPAmZc8rEEE6dsTmuyOXpOU8UL+23aQIo
            Jo/RuQyoaJJm0fr74rR/9eLXXF5IEx+4gOAs1H6K9Ml4dniYDqPKvcpDufOwdLYd
            UGfY5xAU0ET2RcA095nQhS08aeRANgGk57gDdR92B1kO7/2WhjzQMJlh0rGpSpbo
            kNZ0lVyqykChmGOKdwC4TKpLyJiA4jf7JsRnaw6kv23wnU7FCO2nE3UNc5Yvdrxk
            70hScFbbOpTSLHcemnGvgoV1RbbH2qoPI0bBegJfXFYMUNsySNpSJoqNFfrNB07M
            hjoIlNtE3I8BoDJ9Kc3P/twG994A6vg8qwVFlPeSFscjXECSbA3J1Eh/saIjIYcL
            /u9QYSapE7EfuO2Kn92Y8xs5V/F5l9GK+GFHQsatw5DL4LAkeZPREYgT9LUYSABj
            M2HY3uh8exNruCVrfPwviNsvHdN63lQHtW2/yFU1Zy0FCmCqXUr92H3iOm9ZX6JO
            B9b3qZ4z7vbPacJYzhpM72tIX326i80BUr8DxVHGL9O9HjZiwQ2W3H3KJj2TTrvS
            XgFmQy5PW+znH11hlfIbdZwlPSXOpS+b+CICDUfSVLGB/D3NUzm8w3fRtcogt8ex
            BpblNSBzXxsFNML0H7QfSTm17kEu0zPG+3BEixQRDwI/5G3bMA1dCDbWQ58kMKw=
            =a3aJ
            -----END PGP MESSAGE-----
        fp: 618363CE60902D29EFCD5BC8E04F14B3DE5AC01C
    encrypted_regex: ^(data|stringData)$
    version: 3.6.1
