apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: flagger
spec:
  releaseName: flagger
  chart:
    spec:
      chart: flagger
      sourceRef:
        kind: HelmRepository
        name: flagger
        namespace: flux-system
  interval: 1h0m0s
  values:
    meshProvider: nginx
    metricsServer: http://kube-prometheus-stack-prometheus.monitoring:9090
