apiVersion: v1
items:
- apiVersion: monitoring.coreos.com/v1
  kind: ServiceMonitor
  metadata:
    annotations:
      meta.helm.sh/release-name: podinfo
      meta.helm.sh/release-namespace: podinfo
    creationTimestamp: "2021-03-19T13:24:28Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: podinfo
      app.kubernetes.io/version: 5.0.1
      helm.sh/chart: podinfo-5.0.1
    managedFields:
    - apiVersion: monitoring.coreos.com/v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          .: {}
          f:endpoints: {}
          f:selector:
            .: {}
            f:matchLabels:
              .: {}
              f:app: {}
      manager: Go-http-client
      operation: Update
      time: "2021-03-19T13:24:28Z"
    name: podinfo
    namespace: podinfo
    resourceVersion: "727971"
    selfLink: /apis/monitoring.coreos.com/v1/namespaces/podinfo/servicemonitors/podinfo
    uid: dcdd4e23-3a35-42d0-82b3-f76a5e4a2c63
  spec:
    endpoints:
    - interval: 15s
      path: /metrics
      port: http
    selector:
      matchLabels:
        app: podinfo
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
