apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: podinfo
spec:
  releaseName: podinfo
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: "5.0.1" # {"$imagepolicy": "flux-system:podinfo:tag"}
  interval: 5m
  install:
    remediation:
      retries: 3
  values:
    cache: redis-master.redis:6379
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      path: "/"
    # Service Monitor doesn't have matchLabels set correctly
    # serviceMonitor:
    #   enabled: true
    replicaCount: 10
    service:
      enabled: false
