apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  annotations:
    release: podinfo
  labels:
    app.kubernetes.io/name: podinfo
  name: podinfo
  namespace: podinfo
spec:
  endpoints:
  - interval: 15s
    path: /metrics
    port: http
  selector:
    matchLabels:
      app.kubernetes.io/name: podinfo